Repository yiisoft/yii2-gii, pull requests merged in 2019-11, with the labels that each got.

#416 improved generation annotation of properties
  CHANGELOG.md
  src/generators/model/Generator.php
  tests/generators/ModelGeneratorTest.php
Labels: status:ready for merge, type:bug, type:enhancement

#417 bugfix: fixed issue where RTL implementation for foreign keys (e.g. c…
  CHANGELOG.md
  src/generators/model/Generator.php
  tests/data/sqlite.sql
  tests/generators/ModelGeneratorTest.php
Labels: type:bug

#288 Hint with target ActiveQuery class
  CHANGELOG.md
  src/generators/model/Generator.php
  src/generators/model/default/model.php
Labels: status:code review, type:enhancement
